language: r
cache: packages
r: release

env:
    - BIODB_USERAGENT="biodbKegg.test ; pierrick.roger@cea.fr"

notifications:
    email:
        recipients:
            - pierrick.roger@cea.fr

before_install:
    - sudo apt-get install -y libmagick++-dev
    - R -e 'install.packages("BiocManager");BiocManager::install("BiocCheck")'
    - R -e 'install.packages("devtools", dependencies=TRUE)'
    - R -e 'devtools::install_github("pkrog/biodb", ref="master", dependencies=TRUE, build_vignettes=FALSE)'

script:
    - make test
    - make build
    - make full.check || (cat /home/travis/build/pkrog/biodbKegg.Rcheck/tests/testthat.Rout.fail && false)
    - make bioc.check
